name: Run the Tests, Build the image
on:
  push:
    branches: [main] # Consider specifying branches if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Unit Testing
      run: |
        cd ciphers_project
        python manage.py test
